repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: ^.*\.ipynb
    - id: check-added-large-files
    - id: detect-private-key
    - id: check-ast

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations
        # ANN101 - Ignoring self annotation
        # E501 - Clashes with black
        # E203 - : Clashes with black
        args: ["--ignore=ANN101, E501, E203"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        exclude: ^.+\/migrations\/.+

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
